### ISSUE TITLE
SyntaxError on Generic

### ISSUE THREAD

**Issue by lowewenzel** [Botanalyticsco/botanalytics-python#1] opened 2021-01-03 22:32 UTC
Attempting to utilize the Generic module since I need to try this with Telegram. I am getting a Syntax Error coming from the library itself (using Python 3.9):

```
Traceback (most recent call last):
  File "app.py", line 4, in <module>
    from botanalytics.generic import Generic
  File "/env/lib/python3.9/site-packages/botanalytics/generic.py", line 9
    callback=None, async = False):
```

Here is my usage:

```python
botlogger = Generic(debug=True, token=API_KEY)

...
 botlogger.log({
        "user": user.id,
        "is_sender_bot": False,
        "message": message,
    })
```

**Comment by amedat** [comment] 2021-01-22 23:46
Hey, ran into this myself. 

It seems the problem is the  `callback=None, async = False):`
async is a forbidden variable name in Python. 
So if you change it from:
`async` to `async_` it should work. 

change to:
`callback=None, async_ = False):`

**Comment by BeauTaapken** [comment] 2021-07-20 13:55
Hi, just ran into the same problem. This should be fixed. It's a naming issue in the package itself. I can't make my code automatically deploy with this bug

**Closed as completed** 2021-11-16 01:59 UTC

**Comment by dacay** [comment] 2021-11-16 02:02
Thank you for reporting this issue. 

I just committed a fix and will release the new version on PYPI.
